const ElectionDataProd = {
  // Central Region
  "BUIKWE": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 65.99, region:"central" },
  "BUKOMANSIMBI": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 75.87, region:"central" },
  "BUTAMBALA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 76.08, region:"central" },
  "BUVUMA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 50.58, region:"central" },
  "GOMBA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 59.86, region:"central" },
  "KALANGALA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 59.59, region:"central" },
  "KALUNGU": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 69.79, region:"central" },
  "KAMPALA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 72.66, region:"central" },
  "KASANDA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 69.40, region:"central" },
  "KAYUNGA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 66.73, region:"central" },
  "KIBOGA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 56.59, region:"central" },
  "KYANKWANZI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 80.19, region:"central" },
  "KYOTERA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 57.09, region:"central" },
  "LUWERO": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 72.91, region:"central" },
  "LWENGO": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 53.14, region:"central" },
  "LYANTONDE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 56.53, region:"central" },
  "MASAKA CITY": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 74.72, region:"central" },
  "MASAKA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 77.14, region:"central" }, // Note: Separate from Masaka City
  "MITYANA": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 72.68, region:"central" },
  "MPIGI": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 77.64, region:"central" },
  "MUBENDE": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 56.70, region:"central" },
  "MUKONO": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 73.10, region:"central" },
  "NAKASEKE": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 52.29, region:"central" },
  "NAKASONGOLA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 76.47, region:"central" },
  "RAKAI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 51.17, region:"central" },
  "SSEMBABULE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 61.53, region:"central" },
  "WAKISO": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 74.90, region:"central" },

  // Eastern Region
  "AMURIA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 86.64, region:"eastern" },
  "BUDAKA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 76.43, region:"eastern" },
  "BUDUDA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 60.60, region:"eastern" },
  "BUGIRI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 52.29, region:"eastern" },
  "BUGWERI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 70.02, region:"eastern" },
  "BUKEDEA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 89.64, region:"eastern" },
  "BUKWO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 83.19, region:"eastern" },
  "BULAMBULI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 70.86, region:"eastern" },
  "BUSIA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 56.67, region:"eastern" },
  "BUTALEJA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 66.90, region:"eastern" },
  "BUTEBO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 82.47, region:"eastern" },
  "BUYENDE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 82.86, region:"eastern" },
  "IGANGA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 58.88, region:"eastern" },
  "JINJA CITY": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 46.58, region:"eastern" }, // NUP was close here
  "JINJA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 62.51, region:"eastern" }, // Note: Separate from Jinja City
  "KABERAMAIDO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 89.01, region:"eastern" },
  "KALAKI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 91.06, region:"eastern" },
  "KALIRO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 83.11, region:"eastern" },
  "KAMULI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 74.09, region:"eastern" },
  "KAPCHORWA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 80.94, region:"eastern" },
  "KAPELEBYONG": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 90.98, region:"eastern" },
  "KATAKWI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 90.81, region:"eastern" },
  "KIBUKU": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 83.49, region:"eastern" },
  "KUMI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 83.78, region:"eastern" },
  "KWEEN": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 84.77, region:"eastern" },
  "LUUKA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 73.23, region:"eastern" },
  "MANAFWA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 53.44, region:"eastern" },
  "MAYUGE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 60.89, region:"eastern" },
  "MBALE CITY": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 47.27, region:"eastern" }, // NRM was close here // MBALE CITY
  "MBALE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 56.11, region:"eastern" }, // Note: Separate from Mbale City //MBALE DISTRICT
  "NAMAYINGO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 59.80, region:"eastern" },
  "NAMISINDWA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 68.64, region:"eastern" },
  "NAMUTUMBA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 78.42, region:"eastern" },
  "NGORA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 87.34, region:"eastern" },
  "PALLISA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 71.16, region:"eastern" },
  "SERERE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 86.78, region:"eastern" },
  "SIRONKO": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 49.50, region:"eastern" }, // NRM was very close here
  "SOROTI CITY": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 54.89, region:"eastern" },
  "SOROTI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 83.67, region:"eastern" }, // Note: Separate from Soroti City
  "TORORO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 50.37, region:"eastern" },

  // Northern Region
  "ABIM": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 94.25, region:"northern" },
  "ADJUMANI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 81.31, region:"northern" },
  "AGAGO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 53.23, region:"northern" },
  "ALEBTONG": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 71.01, region:"northern" },
  "AMOLATAR": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 77.92, region:"northern" },
  "AMUDAT": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 95.66, region:"northern" },
  "AMURU": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 51.60, region:"northern" },
  "APAC": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 74.86, region:"northern" },
  "ARUA CITY": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 58.28, region:"northern" },
  "ARUA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 76.77, region:"northern" }, // Note: Separate from Arua City //ARUA DISTRICT
  "DOKOLO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 69.17, region:"northern" },
  "GULU CITY": { winner: "NUP", candidate: "Robert Kyagulanyi Ssentamu", percentage: 73.92, region:"northern" },
  "GULU": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 55.69, region:"northern" }, // Note: Separate from Gulu City //GULU DISTRICT
  "KAABONG": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 93.13, region:"northern" },
  "KARENGA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 96.75, region:"northern" },
  "KITGUM": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 59.03, region:"northern" },
  "KOBOKO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 84.86, region:"northern" },
  "KOLE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 63.67, region:"northern" },
  "KOTIDO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 95.98, region:"northern" },
  "KWANIA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 78.88, region:"northern" },
  "LAMWO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 64.27, region:"northern" },
  "LIRA CITY": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 52.36, region:"northern" },
  "LIRA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 70.62, region:"northern" }, // Note: Separate from Lira City //lira district
  "MADI-OKOLLO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 85.13, region:"northern" },
  "MARACHA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 81.45, region:"northern" },
  "MOROTO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 94.66, region:"northern" },
  "MOYO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 79.81, region:"northern" },
  "NABILATUK": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 96.00, region:"northern" },
  "NAKAPIRIPIRIT": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 96.88, region:"northern" },
  "NAPAK": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 95.34, region:"northern" },
  "NEBBI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 70.48, region:"northern" },
  "NWOYA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 63.76, region:"northern" },
  "OBONGI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 82.02, region:"northern" },
  "OMORO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 64.85, region:"northern" },
  "OTUKE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 81.74, region:"northern" },
  "OYAM": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 68.63, region:"northern" },
  "PADER": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 52.17, region:"northern" },
  "PAKWACH": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 66.11, region:"northern" },
  "TEREGO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 86.01, region:"northern" },
  "YUMBE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 86.59, region:"northern" },
  "ZOMBO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 64.55, region:"northern" },

  // Western Region
  "BUHWEJU": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 84.19, region:"western" },
  "BULIISA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 81.83, region:"western" },
  "BUNDIBUGYO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 75.02, region:"western" },
  "BUNYANGABU": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 88.14, region:"western" },
  "BUSHENYI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 80.27, region:"western" },
  "FORT PORTAL CITY": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 80.00, region:"western" }, // Formerly part of Kabarole
  "HOIMA CITY": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 64.98, region:"western" },
  "HOIMA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 80.99, region:"western" }, // Note: Separate from Hoima City
  "IBANDA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 87.20, region:"western" },
  "ISINGIRO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 84.69, region:"western" },
  "KABALE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 74.00, region:"western" },
  "KABAROLE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 88.03, region:"western" }, // Note: Fort Portal City is separate
  "KAGADI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 82.88, region:"western" },
  "KAKUMIRO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 86.57, region:"western" },
  "KAMWENGE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 87.70, region:"western" },
  "KANUNGU": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 78.59, region:"western" },
  "KASESE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 58.61, region:"western" },
  "KAZO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 92.65, region:"western" },
  "KIBAALE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 84.73, region:"western" },
  "KIKUUBE": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 83.10, region:"western" },
  "KIRUHURA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 96.08, region:"western" },
  "KIRYANDONGO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 83.98, region:"western" },
  "KISORO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 91.01, region:"western" },
  "KITAGWENDA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 91.14, region:"western" },
  "KYEGEGWA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 80.37, region:"western" },
  "KYENJOJO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 86.00, region:"western" },
  "MASINDI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 77.83, region:"western" },
  "MBARARA CITY": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 71.44, region:"western" },
  "MBARARA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 87.45, region:"western" }, // Note: Separate from Mbarara City
  "MITOOMA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 85.10, region:"western" },
  "NTOROKO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 86.22, region:"western" },
  "NTUNGAMO": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 76.49, region:"western" },
  "RUBANDA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 81.88, region:"western" },
  "RUBIRIZI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 85.46, region:"western" },
  "RUKIGA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 84.07, region:"western" },
  "RUKUNGIRI": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 59.93, region:"western" }, // FDC's Patrick Amuriat got a significant share here
  "RWAMPARA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 90.44, region:"western" },
  "SHEEMA": { winner: "NRM", candidate: "Yoweri Kaguta Museveni", percentage: 85.35, region:"western" },
};

export default ElectionDataProd; 